# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='board',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
