# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20160822_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='title',
        ),
    ]
